stages:
  - test
  - build
  - deploy

# 所有 stage 之前的操作
before_script:
  - npm set registry https://registry.npm.taobao.org
  - npm install


# 编译
local-build:
  stage: build
  script:
    - npm run build
    - scp -r dist/* root@172.25.10.10:/opt/dev-web-dist/vss
  only:
    - tags
    - 3.x
  tags:
    - node

patch-deploy:
  stage: deploy
  when: manual
  script:
    - npm version minor --unsafe-perm
  only:
    - 3.x
  tags:
    - node
