export default [{
  'id': 'batch-number-manager',
  'parentId': null,
  'label': '批号管理',
  'sort': null,
  'children': [{
    'id': 'batch-number-upload',
    'parentId': 'batch-number-manager',
    'label': '批号关联文件管理',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'batch-number-add',
    'parentId': 'batch-number-manager',
    'label': '新增批号',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'batch-number-download',
    'parentId': 'batch-number-manager',
    'label': '批号关联文件下载',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'batch-number-delete',
    'parentId': 'batch-number-manager',
    'label': '删除批号',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'batch-number-edit',
    'parentId': 'batch-number-manager',
    'label': '编辑批号',
    'sort': null,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}, {
  'id': 'quality-exception-manager',
  'parentId': null,
  'label': '订单异常管理',
  'sort': null,
  'children': [{
    'id': 'quality-exception-edit',
    'parentId': 'quality-exception-manager',
    'label': '提交异常反馈',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'quality-exception-attachment-download',
    'parentId': 'quality-exception-manager',
    'label': '异常附件下载',
    'sort': null,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}, {
  'id': 'purchasing-business',
  'parentId': null,
  'label': '疫苗采购',
  'sort': 1,
  'children': [{
    'id': 'purchasing-contract-manager',
    'parentId': 'purchasing-business',
    'label': '采购合同',
    'sort': 1,
    'children': [{
      'id': 'purchasing-contract-edit',
      'parentId': 'purchasing-contract-manager',
      'label': '修改采购合同',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-contract-add',
      'parentId': 'purchasing-contract-manager',
      'label': '创建采购合同',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-contract-export',
      'parentId': 'purchasing-contract-manager',
      'label': '导出采购合同',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-contract',
      'parentId': 'purchasing-contract-manager',
      'label': '查看采购合同',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'second-vaccine-purchasing-order-manager',
    'parentId': 'purchasing-business',
    'label': '二类苗采购订单',
    'sort': 3,
    'children': [{
      'id': 'second-vaccine-purchasing-order',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '查看二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-purchasing-order-audit',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '审批二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-purchasing-order-cancel',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '取消二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-purchasing-order-batch-audit',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '批量审批二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-purchasing-order-edit',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '编辑二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-purchasing-order-add',
      'parentId': 'second-vaccine-purchasing-order-manager',
      'label': '创建二类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'purchasing-order-manager',
    'parentId': 'purchasing-business',
    'label': '一类苗采购订单',
    'sort': 2,
    'children': [{
      'id': 'purchasing-order-edit',
      'parentId': 'purchasing-order-manager',
      'label': '编辑一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-order',
      'parentId': 'purchasing-order-manager',
      'label': '查看一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-order-audit',
      'parentId': 'purchasing-order-manager',
      'label': '审批一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-order-batch-audit',
      'parentId': 'purchasing-order-manager',
      'label': '批量审批一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-order-cancel',
      'parentId': 'purchasing-order-manager',
      'label': '取消一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchasing-order-add',
      'parentId': 'purchasing-order-manager',
      'label': '创建一类苗采购订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'purchasing-return-manager',
    'parentId': 'purchasing-business',
    'label': '采购退货',
    'sort': 4,
    'children': [{
      'id': 'return-manager-cancel',
      'parentId': 'purchasing-return-manager',
      'label': '取消采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager-audit',
      'parentId': 'purchasing-return-manager',
      'label': '审批采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager-upload-data',
      'parentId': 'purchasing-return-manager',
      'label': '查看反馈信息',
      'sort': null,
      'children': [{
        'id': 'return-manager-upload-data-operate',
        'parentId': 'return-manager-upload-data',
        'label': '上传数据',
        'sort': null,
        'children': null,
        'leaf': true
      }],
      'leaf': false
    }, {
      'id': 'return-manager-edit',
      'parentId': 'purchasing-return-manager',
      'label': '编辑采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager-confirm',
      'parentId': 'purchasing-return-manager',
      'label': '确认采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager-add',
      'parentId': 'purchasing-return-manager',
      'label': '新增采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager',
      'parentId': 'purchasing-return-manager',
      'label': '查看采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'return-manager-batch-audit',
      'parentId': 'purchasing-return-manager',
      'label': '批量审批采购退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'sales-business', 'parentId': null, 'label': '疫苗销售', 'sort': 2, 'children': [{
    'id': 'sales-order-manager',
    'parentId': 'sales-business',
    'label': '一类疫苗销售订单',
    'sort': 1,
    'children': [{
      'id': 'sales-order-delivery-information',
      'parentId': 'sales-order-manager',
      'label': '查看配送信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-batch-audit',
      'parentId': 'sales-order-manager',
      'label': '批量审单一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order',
      'parentId': 'sales-order-manager',
      'label': '查看一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-confirm',
      'parentId': 'sales-order-manager',
      'label': '确认一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-conversion',
      'parentId': 'sales-order-manager',
      'label': '一类疫苗销售订单转换销退订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-upload-data',
      'parentId': 'sales-order-manager',
      'label': '查看反馈信息',
      'sort': null,
      'children': [{
        'id': 'sales-order-upload-data-operate',
        'parentId': 'sales-order-upload-data',
        'label': '上传数据',
        'sort': null,
        'children': null,
        'leaf': true
      }],
      'leaf': false
    }, {
      'id': 'sales-order-add',
      'parentId': 'sales-order-manager',
      'label': '新增一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-audit',
      'parentId': 'sales-order-manager',
      'label': '审单一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-cancel',
      'parentId': 'sales-order-manager',
      'label': '取消一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-order-edit',
      'parentId': 'sales-order-manager',
      'label': '编辑一类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'purchansing-assignment-manager',
    'parentId': 'sales-business',
    'label': '采购汇总',
    'sort': 3,
    'children': [{
      'id': 'purchansing-assignment',
      'parentId': 'purchansing-assignment-manager',
      'label': '查看采购汇总',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'submit-purchansing-plan',
      'parentId': 'purchansing-assignment-manager',
      'label': '生成采购合同',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchansing-assignment-update',
      'parentId': 'purchansing-assignment-manager',
      'label': '编辑采购汇总',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchansing-assignment-add',
      'parentId': 'purchansing-assignment-manager',
      'label': '新增采购汇总',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'sales-return-manager',
    'parentId': 'sales-business',
    'label': '销售退货',
    'sort': 5,
    'children': [{
      'id': 'sales-return-audit',
      'parentId': 'sales-return-manager',
      'label': '审单销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return-edit',
      'parentId': 'sales-return-manager',
      'label': '编辑销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return-batch-audit',
      'parentId': 'sales-return-manager',
      'label': '批量审单销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return',
      'parentId': 'sales-return-manager',
      'label': '查看销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return-add',
      'parentId': 'sales-return-manager',
      'label': '新增销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return-conversion',
      'parentId': 'sales-return-manager',
      'label': '销售退货订单转换销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sales-return-cancel',
      'parentId': 'sales-return-manager',
      'label': '取消销售退货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'second-vaccine-sales-order-manager',
    'parentId': 'sales-business',
    'label': '二类疫苗销售订单',
    'sort': 1,
    'children': [{
      'id': 'second-vaccine-sales-order-delivery-information',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '查看配送信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-upload-data',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '查看反馈信息',
      'sort': null,
      'children': [{
        'id': 'second-vaccine-sales-order-upload-data-operate',
        'parentId': 'second-vaccine-sales-order-upload-data',
        'label': '上传数据',
        'sort': null,
        'children': null,
        'leaf': true
      }],
      'leaf': false
    }, {
      'id': 'second-vaccine-sales-order-cancel',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '取消二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-batch-audit',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '批量审单二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-conversion',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '二类疫苗销售订单转换销退订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-confirm',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '确认二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '查看二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-audit',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '审单二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-edit',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '编辑二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-sales-order-add',
      'parentId': 'second-vaccine-sales-order-manager',
      'label': '新增二类疫苗销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'cerp-create-wave',
    'parentId': 'sales-business',
    'label': '销售分配',
    'sort': 4,
    'children': null,
    'leaf': true
  }, {
    'id': 'no-feedback-order-manager',
    'parentId': 'sales-business',
    'label': '未反馈订单',
    'sort': 6,
    'children': null,
    'leaf': true
  }, {
    'id': 'demand-assignment-manager',
    'parentId': 'sales-business',
    'label': '接种点要货需求',
    'sort': 2,
    'children': [{
      'id': 'pull-signal-generate-order',
      'parentId': 'demand-assignment-manager',
      'label': '要货申请生成销售订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'demand-assignment-update',
      'parentId': 'demand-assignment-manager',
      'label': '编辑接种点要货需求',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'submit-allocation-plan',
      'parentId': 'demand-assignment-manager',
      'label': '提交分配方案',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cargo-signal-add',
      'parentId': 'demand-assignment-manager',
      'label': '新增分货',
      'sort': 7,
      'children': null,
      'leaf': true
    }, {
      'id': 'demand-assignment',
      'parentId': 'demand-assignment-manager',
      'label': '查看接种点要货需求',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'demand-assignment-add',
      'parentId': 'demand-assignment-manager',
      'label': '新增接种点要货需求',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'demand-assignment-cancel',
      'parentId': 'demand-assignment-manager',
      'label': '取消接种点要货需求',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }], 'leaf': false
}, {
  'id': 'pov-business',
  'parentId': null,
  'label': '接种点业务',
  'sort': 3,
  'children': [{
    'id': 'pull-signal-manager',
    'parentId': 'pov-business',
    'label': '要货申请',
    'sort': 1,
    'children': [{
      'id': 'pull-signal-cancel',
      'parentId': 'pull-signal-manager',
      'label': '取消要货申请',
      'sort': 6,
      'children': null,
      'leaf': true
    }, {
      'id': 'pull-signal-audit',
      'parentId': 'pull-signal-manager',
      'label': '审核要货申请',
      'sort': 4,
      'children': null,
      'leaf': true
    }, {
      'id': 'signal-export',
      'parentId': 'pull-signal-manager',
      'label': '导出关联订单',
      'sort': 7,
      'children': null,
      'leaf': true
    }, {
      'id': 'pull-signal-edit',
      'parentId': 'pull-signal-manager',
      'label': '编辑要货申请',
      'sort': 5,
      'children': null,
      'leaf': true
    }, {
      'id': 'pull-signal',
      'parentId': 'pull-signal-manager',
      'label': '查看要货申请',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'pull-signal-add',
      'parentId': 'pull-signal-manager',
      'label': '新增要货申请',
      'sort': 3,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'vaccination-task-manager',
    'parentId': 'pov-business',
    'label': '接种任务管理',
    'sort': 5,
    'children': [{
      'id': 'add-vaccination-task',
      'parentId': 'vaccination-task-manager',
      'label': '创建接种任务',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'edit-vaccination-task',
      'parentId': 'vaccination-task-manager',
      'label': '编辑接种任务',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'cancel-vaccination-task',
      'parentId': 'vaccination-task-manager',
      'label': '取消接种任务',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'query-injection-task',
      'parentId': 'vaccination-task-manager',
      'label': '查看接种任务',
      'sort': 4,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'injection-task-manager',
    'parentId': 'pov-business',
    'label': '注射记录',
    'sort': 60,
    'children': [{
      'id': 'injection-task-export',
      'parentId': 'injection-task-manager',
      'label': '导出注射信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'injection-task-query',
      'parentId': 'injection-task-manager',
      'label': '查看注射信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'subordinate-injection-task-manager',
    'parentId': 'pov-business',
    'label': '下属单位注射记录',
    'sort': 60,
    'children': [{
      'id': 'subordinate-injection-task-query',
      'parentId': 'subordinate-injection-task-manager',
      'label': '查看下属单位注射信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'multi-person-aging',
    'parentId': 'pov-business',
    'label': '多人份剂次时效记录管理',
    'sort': 7,
    'children': [{
      'id': 'query-multi-person-aging',
      'parentId': 'multi-person-aging',
      'label': '查询多人份剂次时效记录',
      'sort': 1,
      'children': null,
      'leaf': true
    }, {
      'id': 'scrap-multi-person-aging',
      'parentId': 'multi-person-aging',
      'label': '报废多人份剂次时效记录',
      'sort': 2,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'inoculator-info-manager',
    'parentId': 'pov-business',
    'label': '接种者档案管理',
    'sort': 4,
    'children': [{
      'id': 'query-inoculator-info',
      'parentId': 'inoculator-info-manager',
      'label': '查询接种者信息',
      'sort': 3,
      'children': null,
      'leaf': true
    }, {
      'id': 'edit-inoculator-info',
      'parentId': 'inoculator-info-manager',
      'label': '编辑接种者信息',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'add-inoculator-info',
      'parentId': 'inoculator-info-manager',
      'label': '新增接种者信息',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'vaccination-units-manager',
    'parentId': 'pov-business',
    'label': '接种台管理',
    'sort': 6,
    'children': [{
      'id': 'confirm-vaccination-task',
      'parentId': 'vaccination-units-manager',
      'label': '确认接种任务',
      'sort': 2,
      'children': null,
      'leaf': true
    }, {
      'id': 'query-vaccination-task',
      'parentId': 'vaccination-units-manager',
      'label': '查看接种台',
      'sort': 1,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'pov-receipt-order-manager',
    'parentId': 'pov-business',
    'label': '收货订单',
    'sort': 2,
    'children': [{
      'id': 'pov-receipt',
      'parentId': 'pov-receipt-order-manager',
      'label': '收货',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'pov-order-upload-data',
      'parentId': 'pov-receipt-order-manager',
      'label': '查看反馈信息',
      'sort': null,
      'children': [{
        'id': 'pov-order-upload-data-operate',
        'parentId': 'pov-order-upload-data',
        'label': '上传数据',
        'sort': null,
        'children': null,
        'leaf': true
      }],
      'leaf': false
    }, {
      'id': 'pov-order-data-sharing',
      'parentId': 'pov-receipt-order-manager',
      'label': '数据共享',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'pov-receipt-manager',
      'parentId': 'pov-receipt-order-manager',
      'label': '查看收货订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'cerp-stock-manager',
  'parentId': null,
  'label': '库存管理',
  'sort': 4,
  'children': [{
    'id': 'erp-stock-inventory',
    'parentId': 'cerp-stock-manager',
    'label': '库存盘点',
    'sort': 6,
    'children': [{
      'id': 'erp-stock-inventory-query',
      'parentId': 'erp-stock-inventory',
      'label': '查看库存盘点',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-stock-inventory-export',
      'parentId': 'erp-stock-inventory',
      'label': '导出库存盘点',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-stock-inventory-operate',
      'parentId': 'erp-stock-inventory',
      'label': '盘点库存数量',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-stock-inventory-add',
      'parentId': 'erp-stock-inventory',
      'label': '创建库存盘点',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-stock-inventory-delete',
      'parentId': 'erp-stock-inventory',
      'label': '删除库存盘点',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'allocating-order-manager',
    'parentId': 'cerp-stock-manager',
    'label': '调拨入库',
    'sort': 7,
    'children': [{
      'id': 'allocating-order-batch-audit',
      'parentId': 'allocating-order-manager',
      'label': '批量审批调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'allocating-order',
      'parentId': 'allocating-order-manager',
      'label': '查看调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'allocating-order-cancel',
      'parentId': 'allocating-order-manager',
      'label': '取消调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'allocating-order-add',
      'parentId': 'allocating-order-manager',
      'label': '创建调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'allocating-order-audit',
      'parentId': 'allocating-order-manager',
      'label': '审批调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'allocating-order-edit',
      'parentId': 'allocating-order-manager',
      'label': '编辑调拨入库订单',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'cerp-stock-pov-regulatory',
    'parentId': 'cerp-stock-manager',
    'label': '接种点库存监管',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'cerp-stock-regulatory',
    'parentId': 'cerp-stock-manager',
    'label': '即时库存监管',
    'sort': 2,
    'children': null,
    'leaf': true
  }, {
    'id': 'cerp-stock-adjust',
    'parentId': 'cerp-stock-manager',
    'label': '库存数量调整',
    'sort': 4,
    'children': null,
    'leaf': true
  }, {
    'id': 'breakage-order-manager',
    'parentId': 'cerp-stock-manager',
    'label': '报损管理',
    'sort': 8,
    'children': [{
      'id': 'breakage-order-add',
      'parentId': 'breakage-order-manager',
      'label': '创建报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-cancel',
      'parentId': 'breakage-order-manager',
      'label': '取消报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-export-scrap-stock-tag',
      'parentId': 'breakage-order-manager',
      'label': '导出待报废疫苗专用标签',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-export-scrap-stock',
      'parentId': 'breakage-order-manager',
      'label': '导出待报废库存登记表',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-document-watch',
      'parentId': 'breakage-order-manager',
      'label': '报损出库附件查看',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-document-upload',
      'parentId': 'breakage-order-manager',
      'label': '报损出库附件上传',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-export-scrap-stock-transport',
      'parentId': 'breakage-order-manager',
      'label': '导出待报废疫苗转运单',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-edit',
      'parentId': 'breakage-order-manager',
      'label': '编辑报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-confirm',
      'parentId': 'breakage-order-manager',
      'label': '确认报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order',
      'parentId': 'breakage-order-manager',
      'label': '查看报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'breakage-order-review-code',
      'parentId': 'breakage-order-manager',
      'label': '复核扫码报损信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'cerp-stock-query',
    'parentId': 'cerp-stock-manager',
    'label': '即时库存',
    'sort': 1,
    'children': null,
    'leaf': true
  }, {
    'id': 'cerp-stock-status-adjust',
    'parentId': 'cerp-stock-manager',
    'label': '库存状态调整',
    'sort': 5,
    'children': [{
      'id': 'cerp-stock-status-adjust-insert',
      'parentId': 'cerp-stock-status-adjust',
      'label': '新增库存状态调整',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'financial-manager',
  'parentId': null,
  'label': '财务管理',
  'sort': 5,
  'children': [{
    'id': 'cdc-advance-payable-manager',
    'parentId': 'financial-manager',
    'label': '预付款管理',
    'sort': 4,
    'children': [{
      'id': 'cdc-advance-payable',
      'parentId': 'cdc-advance-payable-manager',
      'label': '查看付款管理',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'invoice-data-manager',
    'parentId': 'financial-manager',
    'label': '厂商发票管理',
    'sort': 3,
    'children': [{
      'id': 'invoice-add',
      'parentId': 'invoice-data-manager',
      'label': '新增厂商发票',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'invoice-delete',
      'parentId': 'invoice-data-manager',
      'label': '删除厂商发票',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'invoice-manager',
      'parentId': 'invoice-data-manager',
      'label': '查看厂商发票',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'invoice-update',
      'parentId': 'invoice-data-manager',
      'label': '编辑厂商发票',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'vaccine-vendor-reconciliation',
    'parentId': 'financial-manager',
    'label': '疫苗厂商入库明细',
    'sort': 7,
    'children': null,
    'leaf': true
  }, {
    'id': 'accounts-payable-manager',
    'parentId': 'financial-manager',
    'label': '应付账款管理',
    'sort': 1,
    'children': [{
      'id': 'accounts-payable-month-unpaid-info-export',
      'parentId': 'accounts-payable-manager',
      'label': '导出按月汇总未付账款信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'accounts-payable-export',
      'parentId': 'accounts-payable-manager',
      'label': '导出应付账款',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'accounts-payable',
      'parentId': 'accounts-payable-manager',
      'label': '查看应付账款',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'accounts-payable-paid-info-export',
      'parentId': 'accounts-payable-manager',
      'label': '导出已付账款信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'accounts-payable-unpaid-info-export',
      'parentId': 'accounts-payable-manager',
      'label': '导出未付账款信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'pov-payment-payable-manager',
    'parentId': 'financial-manager',
    'label': 'POV付款作业',
    'sort': 4,
    'children': [{
      'id': 'pov-payment-payable-cancel',
      'parentId': 'pov-payment-payable-manager',
      'label': '取消付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'pov-payment-payable',
      'parentId': 'pov-payment-payable-manager',
      'label': '查看付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'pov-payment-payable-add',
      'parentId': 'pov-payment-payable-manager',
      'label': '新增付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'pov-payment-payable-audit',
      'parentId': 'pov-payment-payable-manager',
      'label': '审核付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'pov-advance-receivable-manager',
    'parentId': 'financial-manager',
    'label': '预收款管理',
    'sort': 5,
    'children': [{
      'id': 'pov-advance-receivable',
      'parentId': 'pov-advance-receivable-manager',
      'label': '查看预收款管理',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'cdc-payment-receivable-manager',
    'parentId': 'financial-manager',
    'label': 'CDC收款作业',
    'sort': 4,
    'children': [{
      'id': 'cdc-payment-receivable-review',
      'parentId': 'cdc-payment-receivable-manager',
      'label': '复核收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cdc-payment-receivable-add',
      'parentId': 'cdc-payment-receivable-manager',
      'label': '新增收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cdc-payment-receivable-audit',
      'parentId': 'cdc-payment-receivable-manager',
      'label': '审核收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cdc-payment-receivable',
      'parentId': 'cdc-payment-receivable-manager',
      'label': '查看收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cdc-payment-receivable-cancel',
      'parentId': 'cdc-payment-receivable-manager',
      'label': '取消收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'payment-payable-manager',
    'parentId': 'financial-manager',
    'label': '付款作业',
    'sort': 4,
    'children': [{
      'id': 'payment-payable-allotment',
      'parentId': 'payment-payable-manager',
      'label': '分配付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-payable-audit',
      'parentId': 'payment-payable-manager',
      'label': '审核付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-payable',
      'parentId': 'payment-payable-manager',
      'label': '查看付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-payable-add',
      'parentId': 'payment-payable-manager',
      'label': '新增付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'advance-receivable-manager',
    'parentId': 'financial-manager',
    'label': '预收款作业',
    'sort': 5,
    'children': [{
      'id': 'advance-receivable-cancel',
      'parentId': 'advance-receivable-manager',
      'label': '取消预收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-receivable',
      'parentId': 'advance-receivable-manager',
      'label': '查看预收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-receivable-audit',
      'parentId': 'advance-receivable-manager',
      'label': '审核预收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-receivable-review',
      'parentId': 'advance-receivable-manager',
      'label': '复核预收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-receivable-add',
      'parentId': 'advance-receivable-manager',
      'label': '新增预收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'logistics-vendor-reconciliation',
    'parentId': 'financial-manager',
    'label': '物流商对账',
    'sort': 6,
    'children': null,
    'leaf': true
  }, {
    'id': 'payment-receivable-manager',
    'parentId': 'financial-manager',
    'label': '收款作业',
    'sort': 5,
    'children': [{
      'id': 'payment-receivable-add',
      'parentId': 'payment-receivable-manager',
      'label': '新增收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-receivable',
      'parentId': 'payment-receivable-manager',
      'label': '查看收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-receivable-allotment',
      'parentId': 'payment-receivable-manager',
      'label': '分配收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'payment-receivable-audit',
      'parentId': 'payment-receivable-manager',
      'label': '审核收款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'advance-payable-manager',
    'parentId': 'financial-manager',
    'label': '预付款作业',
    'sort': 4,
    'children': [{
      'id': 'advance-payable-attachment-watch',
      'parentId': 'advance-payable-manager',
      'label': '付款作业附件查看',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-payable-cancel',
      'parentId': 'advance-payable-manager',
      'label': '取消付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-payable-audit',
      'parentId': 'advance-payable-manager',
      'label': '审核付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-payable-add',
      'parentId': 'advance-payable-manager',
      'label': '新增付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-payable',
      'parentId': 'advance-payable-manager',
      'label': '查看付款作业',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'advance-payable-attachment-upload',
      'parentId': 'advance-payable-manager',
      'label': '付款作业附件上传',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'accounts-receivable-manager',
    'parentId': 'financial-manager',
    'label': '应收账款管理',
    'sort': 2,
    'children': [{
      'id': 'accounts-receivable-export',
      'parentId': 'accounts-receivable-manager',
      'label': '导出应收账款',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'accounts-receivable',
      'parentId': 'accounts-receivable-manager',
      'label': '查看应收账款',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'vaccine-batch-process',
  'parentId': null,
  'label': '疫苗批号文件管理',
  'sort': 6,
  'children': [{
    'id': 'vaccine-batch-process-upload',
    'parentId': 'vaccine-batch-process',
    'label': '疫苗批号文件上传',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'vaccine-batch-number-edit',
    'parentId': 'vaccine-batch-process',
    'label': '编辑疫苗批号',
    'sort': null,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}, {
  'id': 'erp-bind-account-manager',
  'parentId': null,
  'label': '组织账户管理',
  'sort': 7,
  'children': [{
    'id': 'erp-system-account-data-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '系统账号管理',
    'sort': 8,
    'children': [{
      'id': 'erp-system-account-export',
      'parentId': 'erp-system-account-data-manager',
      'label': '导出账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-system-account-manager',
      'parentId': 'erp-system-account-data-manager',
      'label': '查看系统账号管理',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-system-account-add',
      'parentId': 'erp-system-account-data-manager',
      'label': '添加账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-system-account-stop',
      'parentId': 'erp-system-account-data-manager',
      'label': '停用账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-system-account-edit',
      'parentId': 'erp-system-account-data-manager',
      'label': '编辑账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-system-account-start',
      'parentId': 'erp-system-account-data-manager',
      'label': '启用账号',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-account-data-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '账号分配',
    'sort': 4,
    'children': [{
      'id': 'erp-account-manager',
      'parentId': 'erp-account-data-manager',
      'label': '查看账号分配',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-account-start',
      'parentId': 'erp-account-data-manager',
      'label': '启用账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-account-add',
      'parentId': 'erp-account-data-manager',
      'label': '添加账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-account-edit',
      'parentId': 'erp-account-data-manager',
      'label': '编辑账号',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-account-stop',
      'parentId': 'erp-account-data-manager',
      'label': '停用账号',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-system-log',
    'parentId': 'erp-bind-account-manager',
    'label': '系统日志',
    'sort': 8,
    'children': [{
      'id': 'erp-platform-user-watch',
      'parentId': 'erp-system-log',
      'label': '查询用户信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-bind-city-pov-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '市疾控绑定接种点',
    'sort': 2,
    'children': [{
      'id': 'erp-bind-city-pov-delete',
      'parentId': 'erp-bind-city-pov-manager',
      'label': '删除绑定接种点',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-city-pov',
      'parentId': 'erp-bind-city-pov-manager',
      'label': '查看市疾控绑定接种点信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-city-pov-add',
      'parentId': 'erp-bind-city-pov-manager',
      'label': '绑定接种点',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-user-data-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '用户管理',
    'sort': 7,
    'children': [{
      'id': 'erp-user-start',
      'parentId': 'erp-user-data-manager',
      'label': '启用用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-user-manager',
      'parentId': 'erp-user-data-manager',
      'label': '查看用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-user-stop',
      'parentId': 'erp-user-data-manager',
      'label': '停用用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-user-edit',
      'parentId': 'erp-user-data-manager',
      'label': '编辑用户',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-user-add',
      'parentId': 'erp-user-data-manager',
      'label': '添加用户',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'access-role-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '角色管理',
    'sort': 5,
    'children': [{
      'id': 'access-role-delete',
      'parentId': 'access-role-manager',
      'label': '删除角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-add',
      'parentId': 'access-role-manager',
      'label': '新增角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-watch',
      'parentId': 'access-role-manager',
      'label': '查看角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-edit',
      'parentId': 'access-role-manager',
      'label': '编辑角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-stop',
      'parentId': 'access-role-manager',
      'label': '停用角色',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'access-role-start',
      'parentId': 'access-role-manager',
      'label': '启用角色',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-bind-pov-data-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '绑定下属接种点',
    'sort': 3,
    'children': [{
      'id': 'erp-bind-pov-manager',
      'parentId': 'erp-bind-pov-data-manager',
      'label': '查看下属接种点信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-pov-delete',
      'parentId': 'erp-bind-pov-data-manager',
      'label': '删除绑定下属接种点',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-pov-add',
      'parentId': 'erp-bind-pov-data-manager',
      'label': '添加绑定下属接种点',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-attachment-name-update',
    'parentId': 'erp-bind-account-manager',
    'label': '编辑附件名称',
    'sort': 9,
    'children': null,
    'leaf': true
  }, {
    'id': 'erp-bind-cdc-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '管理区疾控',
    'sort': 1,
    'children': [{
      'id': 'erp-bind-cdc',
      'parentId': 'erp-bind-cdc-manager',
      'label': '查看区疾控',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-cdc-delete',
      'parentId': 'erp-bind-cdc-manager',
      'label': '删除区疾控',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-cdc-add',
      'parentId': 'erp-bind-cdc-manager',
      'label': '添加绑定区疾控',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'erp-bind-cdc-batch-add',
      'parentId': 'erp-bind-cdc-manager',
      'label': '一键绑定区区疾控和接种点',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'erp-system-manager',
    'parentId': 'erp-bind-account-manager',
    'label': '系统角色管理',
    'sort': 6,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}, {
  'id': 'material-manager',
  'parentId': null,
  'label': '资料管理',
  'sort': 8,
  'children': [{
    'id': 'second-vaccine-info-manager',
    'parentId': 'material-manager',
    'label': '疫苗产品资料',
    'sort': 4,
    'children': [{
      'id': 'second-vaccine-info-update',
      'parentId': 'second-vaccine-info-manager',
      'label': '编辑疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-info-delete',
      'parentId': 'second-vaccine-info-manager',
      'label': '删除疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-info-stop',
      'parentId': 'second-vaccine-info-manager',
      'label': '停用疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-info-start',
      'parentId': 'second-vaccine-info-manager',
      'label': '启用疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-info-add',
      'parentId': 'second-vaccine-info-manager',
      'label': '添加疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-info',
      'parentId': 'second-vaccine-info-manager',
      'label': '查看疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'manufacturer-data-manager',
    'parentId': 'material-manager',
    'label': '疫苗供货厂商资料',
    'sort': 1,
    'children': [{
      'id': 'manufacturer-update',
      'parentId': 'manufacturer-data-manager',
      'label': '编辑疫苗供货厂商资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'manufacturer-add',
      'parentId': 'manufacturer-data-manager',
      'label': '添加疫苗供货厂商资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'manufacturer-start',
      'parentId': 'manufacturer-data-manager',
      'label': '启用疫苗供货厂商资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'manufacturer-stop',
      'parentId': 'manufacturer-data-manager',
      'label': '停用疫苗供货厂商资料',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'manufacturer-manager',
      'parentId': 'manufacturer-data-manager',
      'label': '查看疫苗供货厂商资料',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'first-vaccine-info-manager',
    'parentId': 'material-manager',
    'label': '一类疫苗产品资料',
    'sort': 3,
    'children': [{
      'id': 'first-vaccine-info',
      'parentId': 'first-vaccine-info-manager',
      'label': '查看疫苗产品资料',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'supplies-resources-manager',
    'parentId': 'material-manager',
    'label': '物料管理',
    'sort': 9,
    'children': [{
      'id': 'supplies-delete',
      'parentId': 'supplies-resources-manager',
      'label': '删除物料信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'supplies-add',
      'parentId': 'supplies-resources-manager',
      'label': '添加物料信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'supplies-manager',
      'parentId': 'supplies-resources-manager',
      'label': '查看物料信息',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'supplies-update',
      'parentId': 'supplies-resources-manager',
      'label': '编辑物料信息',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'binding-warehouse-manager',
    'parentId': 'material-manager',
    'label': '仓库管理',
    'sort': 7,
    'children': [{
      'id': 'binding-warehouse-add',
      'parentId': 'binding-warehouse-manager',
      'label': '新增仓库',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'binding-warehouse-start',
      'parentId': 'binding-warehouse-manager',
      'label': '启用仓库',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'binding-warehouse-forbid',
      'parentId': 'binding-warehouse-manager',
      'label': '停用仓库',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'binding-warehouse',
      'parentId': 'binding-warehouse-manager',
      'label': '查看仓库',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'binding-warehouse-update',
      'parentId': 'binding-warehouse-manager',
      'label': '编辑仓库',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'successful-bidder-vaccine-manager',
    'parentId': 'material-manager',
    'label': '中标疫苗',
    'sort': 2,
    'children': [{
      'id': 'successful-bidder-add',
      'parentId': 'successful-bidder-vaccine-manager',
      'label': '添加中标疫苗',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'successful-bidder-vaccine',
      'parentId': 'successful-bidder-vaccine-manager',
      'label': '查看中标疫苗',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'successful-bidder-update',
      'parentId': 'successful-bidder-vaccine-manager',
      'label': '编辑中标疫苗',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'successful-bidder-delete',
      'parentId': 'successful-bidder-vaccine-manager',
      'label': '删除中标疫苗',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'pov-second-authorization-vaccine',
    'parentId': 'material-manager',
    'label': '被授权疫苗',
    'sort': 6,
    'children': null,
    'leaf': true
  }, {
    'id': 'cerp-logistics-cost',
    'parentId': 'material-manager',
    'label': '物流费管理',
    'sort': 8,
    'children': [{
      'id': 'cerp-logistics-cost-add',
      'parentId': 'cerp-logistics-cost',
      'label': '新增物流费',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cerp-logistics-cost-manager',
      'parentId': 'cerp-logistics-cost',
      'label': '查看物流费',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'cerp-logistics-cost-update',
      'parentId': 'cerp-logistics-cost',
      'label': '编辑物流费',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'vaccine-selection',
  'parentId': null,
  'label': '疫苗遴选',
  'sort': 9,
  'children': [{
    'id': 'second-vaccine-authorization-manager',
    'parentId': 'vaccine-selection',
    'label': '二类疫苗接种点授权',
    'sort': 4,
    'children': [{
      'id': 'second-vaccine-authorization',
      'parentId': 'second-vaccine-authorization-manager',
      'label': '查看二类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-authorization-delete',
      'parentId': 'second-vaccine-authorization-manager',
      'label': '删除二类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-authorization-add',
      'parentId': 'second-vaccine-authorization-manager',
      'label': '新增二类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'second-vaccine-authorization-update',
      'parentId': 'second-vaccine-authorization-manager',
      'label': '编辑二类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'first-vaccine-authorization-manager',
    'parentId': 'vaccine-selection',
    'label': '一类疫苗接种点授权',
    'sort': 3,
    'children': [{
      'id': 'first-vaccine-authorization-delete',
      'parentId': 'first-vaccine-authorization-manager',
      'label': '删除一类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'first-vaccine-authorization',
      'parentId': 'first-vaccine-authorization-manager',
      'label': '查看一类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'first-vaccine-authorization-add',
      'parentId': 'first-vaccine-authorization-manager',
      'label': '新增一类疫苗接种单位授权',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'sale-price-group-manager',
    'parentId': 'vaccine-selection',
    'label': '二类疫苗销售价格',
    'sort': 2,
    'children': [{
      'id': 'sale-price-group-add',
      'parentId': 'sale-price-group-manager',
      'label': '新增二类疫苗销售价格',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sale-price-group',
      'parentId': 'sale-price-group-manager',
      'label': '查看二类疫苗销售价格',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sale-price-group-edit',
      'parentId': 'sale-price-group-manager',
      'label': '编辑二类疫苗销售价格',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'sale-price-group-delete',
      'parentId': 'sale-price-group-manager',
      'label': '删除二类疫苗销售价格',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'purchase-agreement-manager',
    'parentId': 'vaccine-selection',
    'label': '区二类疫苗采购目录',
    'sort': 1,
    'children': [{
      'id': 'purchase-agreement',
      'parentId': 'purchase-agreement-manager',
      'label': '查看区二类疫苗采购目录',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchase-agreement-edit',
      'parentId': 'purchase-agreement-manager',
      'label': '编辑区二类疫苗采购目录',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchase-agreement-add',
      'parentId': 'purchase-agreement-manager',
      'label': '新增区二类疫苗采购目录',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'purchase-agreement-delete',
      'parentId': 'purchase-agreement-manager',
      'label': '删除区二类疫苗采购目录',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'report-form-manager',
  'parentId': null,
  'label': '报表管理',
  'sort': 10,
  'children': [{
    'id': 'first-vaccine-logistics-manager',
    'parentId': 'report-form-manager',
    'label': '免费疫苗出入库明细表',
    'sort': 6,
    'children': [{
      'id': 'first-vaccine-logistics-export',
      'parentId': 'first-vaccine-logistics-manager',
      'label': '免费疫苗出入库明细表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'first-vaccine-distribution-manager',
    'parentId': 'report-form-manager',
    'label': '出货货品统计表',
    'sort': 7,
    'children': [{
      'id': 'first-vaccine-distribution-export',
      'parentId': 'first-vaccine-distribution-manager',
      'label': '出货货品统计表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'inventory-form-manager',
    'parentId': 'report-form-manager',
    'label': '进销存盘点表',
    'sort': 4,
    'children': [{
      'id': 'inventory-form-export',
      'parentId': 'inventory-form-manager',
      'label': '进销存盘点表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'each-year-vaccine-manager',
    'parentId': 'report-form-manager',
    'label': '各单位领苗一览表',
    'sort': 13,
    'children': [{
      'id': 'each-year-vaccine-manager-export',
      'parentId': 'each-year-vaccine-manager',
      'label': '各单位领苗一览表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'first-vaccine-out-form-manager',
    'parentId': 'report-form-manager',
    'label': '一类疫苗各区出货统计表',
    'sort': 10,
    'children': [{
      'id': 'first-vaccine-out-form-manager-export',
      'parentId': 'first-vaccine-out-form-manager',
      'label': '一类疫苗各区出货统计表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'cdc-free-vaccine-sale-manager',
    'parentId': 'report-form-manager',
    'label': '一类苗领用记录',
    'sort': 12,
    'children': [{
      'id': 'cdc-free-vaccine-sale-manager-export',
      'parentId': 'cdc-free-vaccine-sale-manager',
      'label': '一类苗领用记录导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'shipment-form-manager',
    'parentId': 'report-form-manager',
    'label': '出货一览表',
    'sort': 3,
    'children': [{
      'id': 'shipment-form-export',
      'parentId': 'shipment-form-manager',
      'label': '出货一览表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'vaccine-month-settlement-manager',
    'parentId': 'report-form-manager',
    'label': '当月疫苗结算表',
    'sort': 11,
    'children': [{
      'id': 'vaccine-month-settlement-manager-export',
      'parentId': 'vaccine-month-settlement-manager',
      'label': '当月疫苗结算表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'drug-administration-data-export-manager',
    'parentId': 'report-form-manager',
    'label': '市药监数据导出',
    'sort': 3,
    'children': [{
      'id': 'drug-administration-out-data-export',
      'parentId': 'drug-administration-data-export-manager',
      'label': '市药监销售数据导出',
      'sort': null,
      'children': null,
      'leaf': true
    }, {
      'id': 'drug-administration-in-data-export',
      'parentId': 'drug-administration-data-export-manager',
      'label': '市药监购进数据导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'month-stock-inventory-form-manager',
    'parentId': 'report-form-manager',
    'label': '二类疫苗月终库存盘点表',
    'sort': 5,
    'children': [{
      'id': 'month-stock-inventory-form-export',
      'parentId': 'month-stock-inventory-form-manager',
      'label': '二类疫苗月终库存盘点表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'purchasing-detail-form-manager',
    'parentId': 'report-form-manager',
    'label': '采购明细表',
    'sort': 1,
    'children': [{
      'id': 'purchasing-detail-form-export',
      'parentId': 'purchasing-detail-form-manager',
      'label': '采购明细表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'stock-in-out-form-manager',
    'parentId': 'report-form-manager',
    'label': '全市出入库明细',
    'sort': 9,
    'children': [{
      'id': 'stock-in-out-form-manager-export',
      'parentId': 'stock-in-out-form-manager',
      'label': '全市出入库明细导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'sale-detail-form-manager',
    'parentId': 'report-form-manager',
    'label': '销售明细表',
    'sort': 2,
    'children': [{
      'id': 'sale-detail-form-export',
      'parentId': 'sale-detail-form-manager',
      'label': '销售明细表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }, {
    'id': 'pov-stock-form-manager',
    'parentId': 'report-form-manager',
    'label': '接种单位疫苗盘点表',
    'sort': 8,
    'children': [{
      'id': 'pov-stock-form-manager-export',
      'parentId': 'pov-stock-form-manager',
      'label': '接种单位疫苗盘点表导出',
      'sort': null,
      'children': null,
      'leaf': true
    }],
    'leaf': false
  }],
  'leaf': false
}, {
  'id': 'erp-other-config',
  'parentId': null,
  'label': '其他设置',
  'sort': 11,
  'children': [{
    'id': 'erp-order-document-watch',
    'parentId': 'erp-other-config',
    'label': '查看订单附件',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'erp-warehouse-temperature-watch',
    'parentId': 'erp-other-config',
    'label': '查看在库温度附件',
    'sort': 3,
    'children': null,
    'leaf': true
  }, {
    'id': 'erp-biz-watch',
    'parentId': 'erp-other-config',
    'label': '查看单位',
    'sort': 2,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}, {
  'id': 'erp-information-manager',
  'parentId': null,
  'label': '信息发布',
  'sort': 12,
  'children': [{
    'id': 'notice-add',
    'parentId': 'erp-information-manager',
    'label': '新增公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-watch',
    'parentId': 'erp-information-manager',
    'label': '查看公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-delete',
    'parentId': 'erp-information-manager',
    'label': '删除公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-issue',
    'parentId': 'erp-information-manager',
    'label': '发布公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-edit',
    'parentId': 'erp-information-manager',
    'label': '编辑公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-stop',
    'parentId': 'erp-information-manager',
    'label': '停用公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-assign',
    'parentId': 'erp-information-manager',
    'label': '指定公告',
    'sort': null,
    'children': null,
    'leaf': true
  }, {
    'id': 'notice-manager',
    'parentId': 'erp-information-manager',
    'label': '公告管理',
    'sort': null,
    'children': null,
    'leaf': true
  }],
  'leaf': false
}];
